### ISSUE TITLE
Exception When Saving Permissions with SQL Server CE

### ISSUE THREAD

**Issue by Nicholas-Westby** [Nicholas-Westby/usergrouppermissions#1]
I got this exception message when saving permissions on a node (the "Blog" node in the "Fanoe" starter kit):
![truncation](https://cloud.githubusercontent.com/assets/5933222/8420008/55382a20-1e73-11e5-918f-13ac8acb5dd9.png)

The important bit of that is:

```
InvalidOperationException: @2 : String truncation: max=0, len=1, value='F'.
```

This is Umbraco 7.2.6 (currently, the latest version of Umbraco).

**Comment by Nicholas-Westby** [comment]
Seems to be related to the fact that UserTypePermission.PermissionId is a char. If I change it to a string, this works fine. Maybe an Umbraco bug having to do with SQL Server CE (I haven't tried with full SQL Server).

**Comment by cwjackso** [comment]
I was using SQL server and didn't run into this issue so it could be SQL CE

**Comment by Nicholas-Westby** [comment]
Yeah, that's my guess. Also, I reported an Umbraco issue for this: http://issues.umbraco.org/issue/U4-6787

**Comment by Nicholas-Westby** [comment]
Fixed by using a string instead of a char in this commit: https://github.com/Nicholas-Westby/usergrouppermissions/commit/1870aba0bd8ff18e4b7f0c3ddaa0f91a2a375a8c
